name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore .\ToDo.Api\ToDo.Api.csproj
    - name: Build
      run: dotnet build .\ToDo.Api\ToDo.Api.csproj --no-restore
    - name: Test
      run: dotnet test .\ToDo.Api.Tests\ToDo.Api.Tests.csproj --verbosity normal

  imaging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ToDo.Api/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapi:latest
      
    - name: Push the docker image to acr registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/todoapi:latest
